#!/bin/sh

docker run -d -p 5000:5000 --restart=always --name registry   -v /var/lib/registry:/var/lib/registry   -e REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io   registry:2
# Don't forget to add this to your Docker.json file (eg. in Docker Desktop => Settings => Docker Engine):
#  "registry-mirrors": [
#    "http://localhost:5000"
#  ]
