#!/bin/sh

set -e

. k8s.include.sh

for rt in $(get_all_non_event_resource_types); do
    result=$(kubectl "$@" get "$rt" 2> /dev/null)
    if [ -n "$result" ]; then
        echo " * $rt:"
        printf -- '%s\n\n' "$result"
    fi
done
